#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.local"

# Writes .env.local by relative path, so it must run from the repo root.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ ! -f "docs/research/apple-signin.md" ]]; then
  printf 'Run this from the bower repo — the research doc was not found.\n' >&2
  exit 1
fi

banner "bower — Sign in with Apple"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Fix the bundle identifier"
say "Everything downstream keys off this one string: the Apple App ID, the"
say "Supabase Client IDs field, and the Xcode target must all carry it."
say ""
warn "It is PERMANENT. The App Store record binds to it at first submission."
say ""
note "  ios/README.md suggests: com.bower.app"
note "  A reverse-DNS domain you control is the convention; bower.com and"
note "  bower.io are both taken by the old JS package manager, so com.bower.app"
note "  is a claim you cannot actually back with a domain."
say ""
say "Safer alternatives if you would rather own the namespace:"
step "com.jadaross.bower"
step "app.bower.ios"
say ""
ask APPLE_BUNDLE_ID "Bundle identifier to use:"
write_env APPLE_BUNDLE_ID "$APPLE_BUNDLE_ID"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Apple Developer — confirm the membership is paid"
say "Sign in with Apple needs a paid Apple Developer Program membership."
say "A free personal team cannot enable the capability."
say ""
note "  You said you hold a Program licence — this stage is a 10-second check,"
note "  not a purchase. Skip it if you are certain."
say ""
open_url "https://developer.apple.com/account"
step "Sign in. Look at the top of the Membership details panel."
step "You want 'Apple Developer Program', with a renewal date."
say ""
ask APPLE_TEAM_ID "While you are here, paste your Team ID (10 characters):"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Apple Developer — register the App ID"
say "This is the ENTIRE Apple-side requirement for native sign-in."
say ""
warn "Do NOT create a Services ID, verify a domain, or generate a .p8 key here."
note "  Every guide you will find leads with those. They belong to the WEB"
note "  OAuth redirect flow. bower is native-only and needs none of them."
note "  Source: docs/research/apple-signin.md §1-2, cited to Apple's own docs."
say ""
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Click + to register a new identifier → App IDs → Continue → App"
step "Description: Bower"
step "Bundle ID: select EXPLICIT, then enter exactly —"
note "      $APPLE_BUNDLE_ID"
step "Scroll the Capabilities list and TICK 'Sign in with Apple'"
step "Continue → Register"
say ""
note "  If the Sign in with Apple checkbox is greyed out, you picked Wildcard"
note "  rather than Explicit. Go back and change it."
pause "Press Enter once the App ID is registered."
if confirm "Is 'Sign in with Apple' ticked on the App ID?"; then
  printf '  %s✓%s Apple side is complete.\n' "$GREEN" "$RESET"
else
  SKIPPED+=("App ID capability — not enabled yet")
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase — enable the Apple provider"
say "Supabase needs the bundle ID so it will accept the native id_token's"
say "'aud' claim. That is what this stage does."
say ""
open_url "https://supabase.com/dashboard/project/_/auth/providers"
step "Pick the bower project → Authentication → Providers → Apple"
step "Toggle 'Enable Sign in with Apple' ON"
step "In 'Client IDs', enter exactly —"
note "      $APPLE_BUNDLE_ID"
say ""
note "  If you ever add a web login later, the Services ID goes FIRST in this"
note "  comma-separated list — Supabase uses the first entry for the web flow,"
note "  while native accepts any entry in the list."
say ""
say "Try to Save now. The next stage handles it if Save refuses."
pause "Press Enter once you have tried to save."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Supabase — the Secret Key workaround"
say "Supabase's own docs say native-only needs no Secret Key. The dashboard"
say "disagrees and may refuse to save without one. That is an acknowledged"
say "bug, not a real requirement — nothing in the native path ever uses it."
say ""
if confirm "Did the provider save WITHOUT a Secret Key?"; then
  printf '  %s✓%s Nothing to do — the bug did not bite. Skipping.\n' "$GREEN" "$RESET"
  pause
else
  warn "You need a throwaway Services ID and key purely to satisfy the form."
  say ""
  open_url "https://developer.apple.com/account/resources/identifiers/list/serviceId"
  step "+ → Services IDs → Continue"
  step "Description: Bower Web (unused) · Identifier: $APPLE_BUNDLE_ID.web"
  step "Register it, reopen it, tick 'Sign in with Apple' → Configure"
  step "Primary App ID: the App ID from stage 3"
  step "Domain: supabase.co · Return URL: your project's callback URL"
  say ""
  open_url "https://developer.apple.com/account/resources/authkeys/list"
  step "+ → tick 'Sign in with Apple' → Configure → pick the primary App ID"
  step "Continue → Register → DOWNLOAD THE .p8 NOW"
  warn "The .p8 can never be downloaded again. Save it somewhere you trust."
  say ""
  ask APPLE_SERVICES_ID "Services ID you created:"
  ask APPLE_KEY_ID "Key ID (10 characters, shown next to the key):"
  write_env APPLE_SERVICES_ID "$APPLE_SERVICES_ID"
  write_env APPLE_KEY_ID "$APPLE_KEY_ID"
  say ""
  say "Now mint the client secret JWT from those, paste it into Supabase's"
  say "Secret Key box, and save."
  note "  ES256 · iss=$APPLE_TEAM_ID · sub=$APPLE_SERVICES_ID"
  note "  aud=https://appleid.apple.com · exp no more than 6 months out"
  warn "It EXPIRES. If you ever ship a web login, it must be regenerated."
  pause "Press Enter once the Apple provider is saved in Supabase."
  SKIPPED+=("Apple client secret expires within 6 months — diarise it")
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Xcode — add the capability"
if ls ios-app/*.xcodeproj >/dev/null 2>&1 || ls ios/*.xcodeproj >/dev/null 2>&1; then
  say "Found an Xcode project. Add the capability to the app target."
  say ""
  step "Select the target → Signing & Capabilities"
  step "+ Capability → Sign in with Apple"
  step "Confirm the bundle identifier reads exactly —"
  note "      $APPLE_BUNDLE_ID"
  say ""
  note "  With Automatic signing, Xcode writes the entitlement and regenerates"
  note "  the provisioning profile for you. With MANUAL signing it does not —"
  note "  you would regenerate the profile yourself."
  pause "Press Enter once the capability is added and the app still builds."
else
  warn "No .xcodeproj found — this stage cannot run yet."
  say ""
  say "That is expected: creating it is issue #11, and it is gated on an open"
  say "decision — whether the app gets a test target (issue #27), which is a"
  say "checkbox at creation time and awkward to add later."
  say ""
  note "  Settle #27, run scripts/setup.sh stage 2 to create the project,"
  note "  then re-run this wizard. It will remember every value above."
  SKIPPED+=("Xcode capability — blocked on #11, which is gated on #27")
  pause
fi

finish
printf '  %sApple and Supabase are configured.%s The remaining work is code:\n' "$BOLD" "$RESET"
printf '  the native ASAuthorizationAppleIDProvider call, exchanged via\n'
printf '  supabase.auth.signInWithIdToken(.apple, idToken:, nonce:).\n\n'
printf '  %sOne open risk%s — issue #30. A private-relay Apple address and an\n' "$YELLOW" "$RESET"
printf '  email/password account for the same person may produce TWO users,\n'
printf '  and so two profiles and two Allowance meters. Decide that before\n'
printf '  both sign-in methods are live.\n\n'
