#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.local"

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ ! -d "ios-app/bower/bower.xcodeproj" ]]; then
  printf 'Run this from the bower repo — the Xcode project was not found.\n' >&2
  exit 1
fi

banner "bower — first TestFlight build"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "What is already done"
say "Every code-side requirement is in the repo and building clean:"
step "App icon, three appearances"
step "Camera and photo-library usage strings"
step "Privacy manifest"
step "Export compliance declared (standard HTTPS only)"
step "Account deletion in Settings — App Review requires it"
step "Privacy policy at a public URL — App Store Connect requires it"
say ""
note "  https://bower-jadas-projects-b3cbda3d.vercel.app/privacy"
say ""
say "What is left is App Store Connect and Xcode's Organizer. Neither can be"
say "driven from here — they need your Apple ID in the room."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect — the app record"
say "This creates the container the build uploads into. It also claims the"
say "name, which is the one thing here that can go wrong."
say ""
open_url "https://appstoreconnect.apple.com/apps"
step "Click + (top left) → New App"
step "Platforms: iOS"
step "Name: bower"
warn "If 'bower' is taken, the form will say so. Try 'bower — sell secondhand'"
warn "or 'bower.' — the name can be changed later, the bundle ID cannot."
step "Primary Language: English (U.K.)"
step "Bundle ID: pick com.jadaross.bower from the dropdown (it is registered)"
step "SKU: bower-ios"
step "User Access: Full Access → Create"
say ""
ask ASC_APP_NAME "The name that was accepted:"
write_env ASC_APP_NAME "$ASC_APP_NAME"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect — App Privacy"
say "Declares what the app collects. It must match the privacy manifest in"
say "the bundle, or review flags the mismatch. This is what the manifest says:"
say ""
open_url "https://appstoreconnect.apple.com/apps"
step "Open $ASC_APP_NAME → App Privacy (left sidebar) → Get Started"
step "Do you collect data? → Yes"
step "Tick exactly two types:"
note "    Contact Info → Email Address"
note "    User Content → Photos or Videos"
step "For EACH of the two, on the next screens:"
note "    Used for: App Functionality only"
note "    Linked to the user's identity: Yes"
note "    Used for tracking: No"
step "Publish"
pause "Press Enter once App Privacy shows as published."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Xcode — archive and upload"
say "Builds a release binary and hands it to App Store Connect."
say ""
step "Open ios-app/bower/bower.xcodeproj in Xcode"
step "Destination (top bar): choose 'Any iOS Device (arm64)' — NOT a simulator"
step "Product → Archive. Wait for it; it takes a minute or two."
step "The Organizer opens. Select the archive → Distribute App"
step "App Store Connect → Upload → Next through the defaults"
note "  Automatic signing is on. It will use team DFFRB59G23."
step "Upload. Wait for 'Upload Successful'."
say ""
warn "Every later upload needs a higher build number. Bump CURRENT_PROJECT_VERSION"
warn "in the target's build settings (1 → 2 → 3…) before each archive."
pause "Press Enter once the upload has succeeded."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect — TestFlight, internal"
say "Processing takes 5–15 minutes after upload. Then the build can be handed"
say "to testers. Internal testing needs NO review — a build is testable the"
say "moment it finishes processing."
say ""
open_url "https://appstoreconnect.apple.com/apps"
step "Open $ASC_APP_NAME → TestFlight tab"
step "Wait for the build under iOS Builds to leave 'Processing'"
step "If it asks about export compliance, it should not — the bundle declares it."
note "  If it does anyway: 'No' to using encryption beyond standard HTTPS."
step "Internal Testing (left) → + → group name: 'bower testers' → Create"
step "Add yourself, then anyone else. They must be App Store Connect users:"
note "  Users and Access → + → add them with the Developer role first."
step "Builds → + → pick the build → Add"
say ""
say "Each tester gets an email. They install the TestFlight app, accept, and"
say "bower appears. Up to 100 internal testers; no review; no expiry beyond 90 days."
pause "Press Enter once at least one tester (you) has the build."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The first real run"
say "Install it on your phone from TestFlight and run the whole flow once:"
say ""
step "Sign in with Apple — a real account is created in Supabase"
step "Pick your platforms, set Depop or Vinted as preferred"
step "Photograph something you own. Have a squiz."
step "You should get a guess in ~8 seconds. Tap 'Get a real price'."
step "Copy the listing. Paste it into Vinted. That is v1."
say ""
say "If sign-in fails: check Supabase → Authentication → Providers → Apple has"
say "com.jadaross.bower in Client IDs. That is the only config that can be wrong."
say ""
if confirm "Did the whole flow work on your phone?"; then
  printf '  %s✓%s bower v1 is live on TestFlight.\n' "$GREEN" "$RESET"
else
  SKIPPED+=("First real run — something failed; tell Claude what you saw")
fi

finish
printf '  %sNext rung%s — issue #29 has the ladder. External TestFlight and the App\n' "$BOLD" "$RESET"
printf '  Store need Beta App Review, screenshots, a support URL and an age rating.\n'
printf '  Everything code-side for that is already in the bundle.\n\n'
